[package]
name = "skyfall_testing"
version = "0.1.0"
edition = "2024"

[dependencies]
libskyfall = {workspace = true}
tokio = {workspace = true, features = ["full"]}
iroh = { workspace = true, features = ["discovery-local-network", "discovery-pkarr-dht"] }
